@startuml
class Etudiant {
    numEtudiant
    nom
    prenom
    dateDeNaissance
} 

class Cours {
    titre
    corpsModule
}

 class Enseignant {
     nomE
     prenomE
 }

 class Examens {
     date
     coefficient
 }
 
  Etudiant "0..*"--->"1" Examens
 Enseignant "1" ---> "*" Cours
 Etudiant "0..*" --> "1"Cours
@enduml
